CREATE DATABASE IF NOT EXISTS DATABASEX;
USE DATABASEX;

CREATE TABLE control (
    id INT AUTO_INCREMENT NOT NULL,
    url VARCHAR(100),
    minutos VARCHAR(255),
    CONSTRAINT pk_usuarios PRIMARY KEY (id)
) ENGINE=InnoDB;
